Automatic compile on PR (#36)
Update deploy workflow to include PR handling and Kobweb build

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,12 +1,38 @@
 on:
-    workflow_dispatch:
-    push:
-        branches:
-            - main
-            - github-docker-cache
+  workflow_dispatch:
+  push:
+    branches:
+      - main
+      - deploy
+      - docker-build-switch
+  pull_request:
+    types: [ opened, synchronize, reopened ]
 
-jobs:
+  jobs:
+    compile:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+        - name: Set up JDK 21
+          uses: actions/setup-java@v4
+          with:
+            java-version: '21'
+            distribution: 'temurin'
+        - name: Setup Gradle
+          uses: gradle/actions/setup-gradle@v3
+        - name: Make Gradle wrapper executable
+          run: chmod +x ./gradlew
+        - name: Compile Kobweb project
+          run: ./gradlew site:kobwebExport -PkobwebExportLayout=STATIC -PkobwebReuseServer=false -PkobwebBuildTarget=RELEASE --stacktrace
+        - name: Check for compilation errors
+          run: |
+            if [ $? -ne 0 ]; then
+              echo "Kobweb compilation failed!"
+              exit 1
+            fi
     build:
+        if: github.event_name != 'pull_request'
         runs-on: ubuntu-latest
         steps:
             -
@@ -57,21 +83,16 @@ jobs:
                 run: ./deploy/build.sh
 
     deploy:
-        needs: build
-        runs-on: ubuntu-latest
-        steps:
-            -
-                uses: actions/checkout@v4
-            -
-                name: Install SSH key
-                uses: shimataro/ssh-key-action@v2
-                with:
-                    key: ${{ secrets.SWARM_SSH_PRIVATE_KEY }}
-                    known_hosts: server.zenmo.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ1E4LUG22qgzc8U7oNYGWCn0cyA31+iyX2pck9wcPMS
-            -
-                name: docker context create
-                run: docker context create zenmoswarm --docker "host=ssh://root@server.zenmo.com"
-            -
-                run: docker context use zenmoswarm
-            -
-                run: ./deploy/deploy.sh
+      needs: build
+      runs-on: ubuntu-latest
+      steps:
+        - uses: actions/checkout@v4
+        - name: Install SSH key
+          uses: shimataro/ssh-key-action@v2
+          with:
+            key: ${{ secrets.SWARM_SSH_PRIVATE_KEY }}
+            known_hosts: server.zenmo.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ1E4LUG22qgzc8U7oNYGWCn0cyA31+iyX2pck9wcPMS
+        - name: docker context create
+          run: docker context create zenmoswarm --docker "host=ssh://root@server.zenmo.com"
+        - run: docker context use zenmoswarm
+        - run: ./deploy/deploy.sh
